//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace measure.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM 2")]
        public string keithley_com_port {
            get {
                return ((string)(this["keithley_com_port"]));
            }
            set {
                this["keithley_com_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57600")]
        public int keithley_speed {
            get {
                return ((int)(this["keithley_speed"]));
            }
            set {
                this["keithley_speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int keithley_data_bits {
            get {
                return ((int)(this["keithley_data_bits"]));
            }
            set {
                this["keithley_data_bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OnePointFive")]
        public global::System.IO.Ports.StopBits keithley_stop_bits {
            get {
                return ((global::System.IO.Ports.StopBits)(this["keithley_stop_bits"]));
            }
            set {
                this["keithley_stop_bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Even")]
        public global::System.IO.Ports.Parity keithley_parity {
            get {
                return ((global::System.IO.Ports.Parity)(this["keithley_parity"]));
            }
            set {
                this["keithley_parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XOnXOff")]
        public global::System.IO.Ports.Handshake keithley_flow_control {
            get {
                return ((global::System.IO.Ports.Handshake)(this["keithley_flow_control"]));
            }
            set {
                this["keithley_flow_control"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM 4")]
        public string agilent_com_port {
            get {
                return ((string)(this["agilent_com_port"]));
            }
            set {
                this["agilent_com_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int agilent_speed {
            get {
                return ((int)(this["agilent_speed"]));
            }
            set {
                this["agilent_speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int agilent_data_bits {
            get {
                return ((int)(this["agilent_data_bits"]));
            }
            set {
                this["agilent_data_bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OnePointFive")]
        public global::System.IO.Ports.StopBits agilent_stop_bits {
            get {
                return ((global::System.IO.Ports.StopBits)(this["agilent_stop_bits"]));
            }
            set {
                this["agilent_stop_bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Odd")]
        public global::System.IO.Ports.Parity agilent_parity {
            get {
                return ((global::System.IO.Ports.Parity)(this["agilent_parity"]));
            }
            set {
                this["agilent_parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RequestToSend")]
        public global::System.IO.Ports.Handshake agilent_flow_control {
            get {
                return ((global::System.IO.Ports.Handshake)(this["agilent_flow_control"]));
            }
            set {
                this["agilent_flow_control"] = value;
            }
        }
    }
}
